# Generated by Django 4.2.28 on 2026-07-02 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scheduler", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledtask",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="scheduledtask",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scheduled_tasks",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="cronschedule",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cron_schedules",
                to="tenants.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="taskexecution",
            index=models.Index(
                fields=["task", "status"], name="scheduler_t_task_id_11c54d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskexecution",
            index=models.Index(
                fields=["started_at"], name="scheduler_t_started_100a08_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskexecution",
            index=models.Index(
                fields=["celery_task_id"], name="scheduler_t_celery__192c03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledtask",
            index=models.Index(
                fields=["status", "enabled", "next_run"],
                name="scheduler_s_status_55aae3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledtask",
            index=models.Index(
                fields=["tenant", "status"], name="scheduler_s_tenant__19f1d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledtask",
            index=models.Index(
                fields=["task_name"], name="scheduler_s_task_na_191e63_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cronschedule",
            unique_together={("tenant", "name")},
        ),
    ]
