# Generated by Django 4.2.28 on 2026-07-02 08:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Experiment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("base_config", models.JSONField(default=dict)),
                ("hyperparameters", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("best_metric_name", models.CharField(default="loss", max_length=100)),
                ("best_metric_value", models.FloatField(blank=True, null=True)),
                ("best_metric_minimize", models.BooleanField(default=True)),
                ("tags", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "experiments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HyperparameterSweep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("grid", "Grid Search"),
                            ("random", "Random Search"),
                            ("bayesian", "Bayesian Optimization"),
                            ("hyperband", "Hyperband"),
                        ],
                        default="random",
                        max_length=20,
                    ),
                ),
                ("parameter_space", models.JSONField()),
                ("objective_metric", models.CharField(default="loss", max_length=100)),
                ("objective_minimize", models.BooleanField(default=True)),
                ("max_trials", models.IntegerField(default=10)),
                ("max_parallel_trials", models.IntegerField(default=2)),
                ("early_stopping_patience", models.IntegerField(default=5)),
                ("completed_trials", models.IntegerField(default=0)),
                ("best_trial_params", models.JSONField(blank=True, null=True)),
                ("best_trial_value", models.FloatField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "hyperparameter_sweeps",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ModelArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "artifact_type",
                    models.CharField(
                        choices=[
                            ("checkpoint", "Checkpoint"),
                            ("final", "Final Model"),
                            ("onnx", "ONNX Export"),
                            ("tensorrt", "TensorRT"),
                            ("torchscript", "TorchScript"),
                        ],
                        default="checkpoint",
                        max_length=20,
                    ),
                ),
                ("file_path", models.CharField(max_length=500)),
                ("file_size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("checksum", models.CharField(blank=True, max_length=64)),
                ("step", models.IntegerField(blank=True, null=True)),
                ("epoch", models.IntegerField(blank=True, null=True)),
                ("metrics", models.JSONField(default=dict)),
                ("model_architecture", models.CharField(blank=True, max_length=255)),
                ("parameter_count", models.BigIntegerField(blank=True, null=True)),
                ("framework_version", models.CharField(blank=True, max_length=50)),
                ("is_best", models.BooleanField(default=False)),
                ("is_final", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "model_artifacts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "framework",
                    models.CharField(
                        choices=[
                            ("pytorch", "PyTorch"),
                            ("tensorflow", "TensorFlow"),
                            ("jax", "JAX"),
                            ("deepspeed", "DeepSpeed"),
                            ("megatron", "Megatron-LM"),
                        ],
                        default="pytorch",
                        max_length=20,
                    ),
                ),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("data_parallel", "Data Parallel (DDP)"),
                            ("model_parallel", "Model Parallel"),
                            ("pipeline_parallel", "Pipeline Parallel"),
                            ("tensor_parallel", "Tensor Parallel"),
                            ("fsdp", "Fully Sharded Data Parallel"),
                            ("zero", "ZeRO Optimization"),
                        ],
                        default="data_parallel",
                        max_length=20,
                    ),
                ),
                ("code_repository", models.URLField(blank=True)),
                ("code_branch", models.CharField(default="main", max_length=100)),
                ("code_commit", models.CharField(blank=True, max_length=40)),
                ("docker_image", models.CharField(blank=True, max_length=255)),
                ("entry_point", models.CharField(max_length=500)),
                ("arguments", models.JSONField(default=dict)),
                ("environment", models.JSONField(default=dict)),
                ("gpu_count", models.IntegerField(default=1)),
                ("gpu_type", models.CharField(blank=True, max_length=50)),
                ("nodes_count", models.IntegerField(default=1)),
                ("memory_gb", models.IntegerField(default=64)),
                ("storage_gb", models.IntegerField(default=100)),
                ("world_size", models.IntegerField(default=1)),
                ("gradient_accumulation_steps", models.IntegerField(default=1)),
                (
                    "mixed_precision",
                    models.CharField(
                        choices=[("fp32", "FP32"), ("fp16", "FP16"), ("bf16", "BF16")],
                        default="fp16",
                        max_length=10,
                    ),
                ),
                ("distributed_config", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("queued", "Queued"),
                            ("initializing", "Initializing"),
                            ("running", "Running"),
                            ("checkpointing", "Checkpointing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("preempted", "Preempted"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("priority", models.IntegerField(default=5)),
                ("preemptible", models.BooleanField(default=False)),
                ("worker_hosts", models.JSONField(default=list)),
                ("master_addr", models.CharField(blank=True, max_length=255)),
                ("master_port", models.IntegerField(default=29500)),
                ("current_epoch", models.IntegerField(default=0)),
                ("total_epochs", models.IntegerField(default=1)),
                ("current_step", models.IntegerField(default=0)),
                ("total_steps", models.IntegerField(blank=True, null=True)),
                ("progress_percent", models.FloatField(default=0)),
                ("metrics", models.JSONField(default=dict)),
                ("last_loss", models.FloatField(blank=True, null=True)),
                ("best_loss", models.FloatField(blank=True, null=True)),
                ("learning_rate", models.FloatField(blank=True, null=True)),
                ("throughput_samples_sec", models.FloatField(blank=True, null=True)),
                ("checkpoint_enabled", models.BooleanField(default=True)),
                ("checkpoint_interval_steps", models.IntegerField(default=1000)),
                ("checkpoint_path", models.CharField(blank=True, max_length=500)),
                ("latest_checkpoint", models.CharField(blank=True, max_length=500)),
                (
                    "resume_from_checkpoint",
                    models.CharField(blank=True, max_length=500),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("estimated_completion", models.DateTimeField(blank=True, null=True)),
                ("max_runtime_hours", models.IntegerField(default=24)),
                ("output_path", models.CharField(blank=True, max_length=500)),
                ("logs_path", models.CharField(blank=True, max_length=500)),
                ("tensorboard_path", models.CharField(blank=True, max_length=500)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("max_retries", models.IntegerField(default=3)),
                ("tags", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allocation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="training_jobs",
                        to="resources.resourceallocation",
                    ),
                ),
            ],
            options={
                "db_table": "training_jobs",
                "ordering": ["-priority", "-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("run_number", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("queued", "Queued"),
                            ("initializing", "Initializing"),
                            ("running", "Running"),
                            ("checkpointing", "Checkpointing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("preempted", "Preempted"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("final_loss", models.FloatField(blank=True, null=True)),
                ("final_metrics", models.JSONField(default=dict)),
                ("exit_code", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("logs", models.TextField(blank=True)),
                ("final_checkpoint", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="training.trainingjob",
                    ),
                ),
            ],
            options={
                "db_table": "training_runs",
                "ordering": ["job", "run_number"],
            },
        ),
    ]
