# Generated by Django 4.2.28 on 2026-07-02 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0002_initial"),
        ("training", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingjob",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_training_jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="trainingjob",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="training_jobs",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="modelartifact",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artifacts",
                to="training.trainingjob",
            ),
        ),
        migrations.AddField(
            model_name="hyperparametersweep",
            name="experiment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sweeps",
                to="training.experiment",
            ),
        ),
        migrations.AddField(
            model_name="experiment",
            name="best_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="training.trainingjob",
            ),
        ),
        migrations.AddField(
            model_name="experiment",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="experiment",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="experiments",
                to="tenants.tenant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="trainingrun",
            unique_together={("job", "run_number")},
        ),
        migrations.AddIndex(
            model_name="trainingjob",
            index=models.Index(
                fields=["tenant", "status"], name="training_jo_tenant__710828_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trainingjob",
            index=models.Index(
                fields=["status", "priority"], name="training_jo_status_7fbb64_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trainingjob",
            index=models.Index(
                fields=["framework", "status"], name="training_jo_framewo_4dda0f_idx"
            ),
        ),
    ]
