"""SQL query support for StreamAnalytics.

Provides SQL parsing, logical optimization, and physical planning
for stream and batch query processing.
"""

from .parser import SQLParser, SQLLexer, Token, TokenType
from .ast import (
    Expression,
    ColumnRef,
    Literal,
    BinaryOp,
    UnaryOp,
    FunctionCall,
    AggregateExpr,
    CaseExpr,
    SubqueryExpr,
    SelectStatement,
    FromClause,
    JoinClause,
    WhereClause,
    GroupByClause,
    HavingClause,
    OrderByClause,
    TableRef,
)
from .logical import (
    LogicalPlan,
    LogicalScan,
    LogicalFilter,
    LogicalProject,
    LogicalJoin,
    LogicalAggregate,
    LogicalSort,
    LogicalLimit,
    LogicalUnion,
    LogicalPlanBuilder,
)
from .optimizer import (
    LogicalOptimizer,
    OptimizationRule,
    PredicatePushdown,
    ProjectionPruning,
    JoinReordering,
    ConstantFolding,
    CommonSubexpressionElimination,
)
from .planner import (
    PhysicalPlan,
    PhysicalScan,
    PhysicalFilter,
    PhysicalProject,
    PhysicalHashJoin,
    PhysicalBroadcastJoin,
    PhysicalMergeJoin,
    PhysicalAggregate,
    PhysicalSort,
    PhysicalLimit,
    PhysicalExchange,
    PhysicalPlanner,
    JoinStrategy,
    DistributionType,
)
from .cost_model import (
    CostConstants,
    ColumnStatistics,
    TableStatistics,
    StatisticsEstimator,
    OperatorCost,
    CostModel,
    JoinNode,
    JoinEdge,
    DPJoinOptimizer,
    CostBasedJoinReordering,
    CostBasedPhysicalPlanner,
    CostBasedOptimizer,
)

__all__ = [
    # Parser
    "SQLParser",
    "SQLLexer",
    "Token",
    "TokenType",
    # AST
    "Expression",
    "ColumnRef",
    "Literal",
    "BinaryOp",
    "UnaryOp",
    "FunctionCall",
    "AggregateExpr",
    "CaseExpr",
    "SubqueryExpr",
    "SelectStatement",
    "FromClause",
    "JoinClause",
    "WhereClause",
    "GroupByClause",
    "HavingClause",
    "OrderByClause",
    "TableRef",
    # Logical Plan
    "LogicalPlan",
    "LogicalScan",
    "LogicalFilter",
    "LogicalProject",
    "LogicalJoin",
    "LogicalAggregate",
    "LogicalSort",
    "LogicalLimit",
    "LogicalUnion",
    "LogicalPlanBuilder",
    # Optimizer
    "LogicalOptimizer",
    "OptimizationRule",
    "PredicatePushdown",
    "ProjectionPruning",
    "JoinReordering",
    "ConstantFolding",
    "CommonSubexpressionElimination",
    # Physical Planner
    "PhysicalPlan",
    "PhysicalScan",
    "PhysicalFilter",
    "PhysicalProject",
    "PhysicalHashJoin",
    "PhysicalBroadcastJoin",
    "PhysicalMergeJoin",
    "PhysicalAggregate",
    "PhysicalSort",
    "PhysicalLimit",
    "PhysicalExchange",
    "PhysicalPlanner",
    "JoinStrategy",
    "DistributionType",
    # Cost Model
    "CostConstants",
    "ColumnStatistics",
    "TableStatistics",
    "StatisticsEstimator",
    "OperatorCost",
    "CostModel",
    "JoinNode",
    "JoinEdge",
    "DPJoinOptimizer",
    "CostBasedJoinReordering",
    "CostBasedPhysicalPlanner",
    "CostBasedOptimizer",
]
