# Generated by Django 4.2.28 on 2026-07-02 08:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ComputeNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("hostname", models.CharField(max_length=255, unique=True)),
                (
                    "gpu_type",
                    models.CharField(
                        choices=[
                            ("a100_40gb", "NVIDIA A100 40GB"),
                            ("a100_80gb", "NVIDIA A100 80GB"),
                            ("h100", "NVIDIA H100"),
                            ("l40s", "NVIDIA L40S"),
                            ("a10g", "NVIDIA A10G"),
                            ("t4", "NVIDIA T4"),
                        ],
                        max_length=50,
                    ),
                ),
                ("gpu_count", models.IntegerField(default=1)),
                ("gpu_memory_gb", models.IntegerField()),
                ("cpu_cores", models.IntegerField()),
                ("ram_gb", models.IntegerField()),
                ("storage_tb", models.DecimalField(decimal_places=2, max_digits=5)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("region", models.CharField(max_length=50)),
                ("availability_zone", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("allocated", "Allocated"),
                            ("maintenance", "Under Maintenance"),
                            ("offline", "Offline"),
                            ("reserved", "Reserved"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("health_status", models.JSONField(default=dict)),
                ("last_health_check", models.DateTimeField(blank=True, null=True)),
                (
                    "price_per_hour",
                    models.IntegerField(help_text="Price per hour in cents"),
                ),
                ("tags", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "compute_nodes",
                "ordering": ["region", "name"],
            },
        ),
        migrations.CreateModel(
            name="GPU",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("device_index", models.IntegerField()),
                (
                    "gpu_type",
                    models.CharField(
                        choices=[
                            ("a100_40gb", "NVIDIA A100 40GB"),
                            ("a100_80gb", "NVIDIA A100 80GB"),
                            ("h100", "NVIDIA H100"),
                            ("l40s", "NVIDIA L40S"),
                            ("a10g", "NVIDIA A10G"),
                            ("t4", "NVIDIA T4"),
                        ],
                        max_length=50,
                    ),
                ),
                ("memory_gb", models.IntegerField()),
                ("cuda_version", models.CharField(blank=True, max_length=20)),
                ("driver_version", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("allocated", "Allocated"),
                            ("maintenance", "Under Maintenance"),
                            ("offline", "Offline"),
                            ("reserved", "Reserved"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("temperature_celsius", models.IntegerField(blank=True, null=True)),
                ("memory_used_gb", models.FloatField(blank=True, null=True)),
                ("utilization_percent", models.IntegerField(blank=True, null=True)),
                ("power_watts", models.IntegerField(blank=True, null=True)),
                ("metrics_updated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "gpus",
                "ordering": ["node", "device_index"],
            },
        ),
        migrations.CreateModel(
            name="ResourceAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("requested_gpus", models.IntegerField(default=1)),
                ("requested_memory_gb", models.IntegerField(blank=True, null=True)),
                ("requested_cpu_cores", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("preempted", "Preempted"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        choices=[
                            (1, "Low"),
                            (5, "Normal"),
                            (10, "High"),
                            (20, "Critical"),
                        ],
                        default=5,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("max_duration_hours", models.IntegerField(default=24)),
                ("preemptible", models.BooleanField(default=False)),
                ("job_id", models.CharField(blank=True, max_length=255)),
                ("job_type", models.CharField(blank=True, max_length=50)),
                ("estimated_cost_cents", models.IntegerField(blank=True, null=True)),
                ("actual_cost_cents", models.IntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "resource_allocations",
                "ordering": ["-priority", "requested_at"],
            },
        ),
        migrations.CreateModel(
            name="ResourceQuota",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("max_gpus", models.IntegerField(default=4)),
                ("max_gpu_hours_monthly", models.IntegerField(default=100)),
                ("max_concurrent_jobs", models.IntegerField(default=5)),
                ("max_storage_gb", models.IntegerField(default=100)),
                ("current_gpus_allocated", models.IntegerField(default=0)),
                ("gpu_hours_used_this_month", models.FloatField(default=0)),
                ("current_jobs_running", models.IntegerField(default=0)),
                ("storage_used_gb", models.IntegerField(default=0)),
                ("monthly_budget_cents", models.IntegerField(blank=True, null=True)),
                ("current_month_spent_cents", models.IntegerField(default=0)),
                ("usage_reset_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "resource_quotas",
            },
        ),
        migrations.CreateModel(
            name="ResourceReservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "gpu_type",
                    models.CharField(
                        choices=[
                            ("a100_40gb", "NVIDIA A100 40GB"),
                            ("a100_80gb", "NVIDIA A100 80GB"),
                            ("h100", "NVIDIA H100"),
                            ("l40s", "NVIDIA L40S"),
                            ("a10g", "NVIDIA A10G"),
                            ("t4", "NVIDIA T4"),
                        ],
                        max_length=50,
                    ),
                ),
                ("gpu_count", models.IntegerField(default=1)),
                ("region", models.CharField(blank=True, max_length=50)),
                (
                    "reservation_type",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("recurring", "Recurring"),
                            ("on_demand", "On-Demand"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("recurring_schedule", models.JSONField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("discount_percent", models.IntegerField(default=0)),
                ("prepaid_amount_cents", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allocation",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservation",
                        to="resources.resourceallocation",
                    ),
                ),
            ],
            options={
                "db_table": "resource_reservations",
                "ordering": ["starts_at"],
            },
        ),
    ]
