# Generated by Django 4.2.28 on 2026-07-02 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcereservation",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="resourcereservation",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resource_reservations",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="resourcequota",
            name="tenant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resource_quota",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="resourceallocation",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resource_allocations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="resourceallocation",
            name="node",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allocations",
                to="resources.computenode",
            ),
        ),
        migrations.AddField(
            model_name="resourceallocation",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resource_allocations",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="gpu",
            name="current_allocation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="allocated_gpus",
                to="resources.resourceallocation",
            ),
        ),
        migrations.AddField(
            model_name="gpu",
            name="node",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gpus",
                to="resources.computenode",
            ),
        ),
        migrations.AddIndex(
            model_name="computenode",
            index=models.Index(
                fields=["gpu_type", "status"], name="compute_nod_gpu_typ_8f5154_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="computenode",
            index=models.Index(
                fields=["region", "status"], name="compute_nod_region_2438c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resourceallocation",
            index=models.Index(
                fields=["tenant", "status"], name="resource_al_tenant__81a94f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resourceallocation",
            index=models.Index(
                fields=["node", "status"], name="resource_al_node_id_04d24c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resourceallocation",
            index=models.Index(
                fields=["status", "priority"], name="resource_al_status_f53d4f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="gpu",
            unique_together={("node", "device_index")},
        ),
    ]
