"""Alert management for feature platform."""

from dataclasses import dataclass, field
from datetime import datetime, timedelta
from enum import Enum
from typing import Any, Callable, Dict, List, Optional
import logging


class AlertSeverity(Enum):
    """Severity levels for alerts."""

    INFO = "info"
    WARNING = "warning"
    ERROR = "error"
    CRITICAL = "critical"


class AlertStatus(Enum):
    """Status of an alert."""

    ACTIVE = "active"
    ACKNOWLEDGED = "acknowledged"
    RESOLVED = "resolved"


@dataclass
class Alert:
    """An alert generated by the system."""

    alert_id: str
    severity: AlertSeverity
    title: str
    message: str
    source: str
    created_at: datetime = field(default_factory=datetime.utcnow)
    status: AlertStatus = AlertStatus.ACTIVE
    metadata: Dict[str, Any] = field(default_factory=dict)
    acknowledged_at: Optional[datetime] = None
    acknowledged_by: Optional[str] = None
    resolved_at: Optional[datetime] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "alert_id": self.alert_id,
            "severity": self.severity.value,
            "title": self.title,
            "message": self.message,
            "source": self.source,
            "created_at": self.created_at.isoformat(),
            "status": self.status.value,
            "metadata": self.metadata,
        }

    def acknowledge(self, user: str) -> None:
        """Acknowledge the alert."""
        self.status = AlertStatus.ACKNOWLEDGED
        self.acknowledged_at = datetime.utcnow()
        self.acknowledged_by = user

    def resolve(self) -> None:
        """Resolve the alert."""
        self.status = AlertStatus.RESOLVED
        self.resolved_at = datetime.utcnow()


@dataclass
class AlertRule:
    """Rule for generating alerts."""

    name: str
    condition: Callable[[Dict[str, Any]], bool]
    severity: AlertSeverity
    title_template: str
    message_template: str
    cooldown_minutes: int = 15
    enabled: bool = True

    _last_triggered: Optional[datetime] = field(default=None, repr=False)

    def can_trigger(self) -> bool:
        """Check if the rule can trigger based on cooldown."""
        if not self.enabled:
            return False
        if self._last_triggered is None:
            return True
        cooldown = timedelta(minutes=self.cooldown_minutes)
        return datetime.utcnow() - self._last_triggered > cooldown

    def trigger(self, context: Dict[str, Any]) -> Optional[Alert]:
        """Trigger the rule if condition is met."""
        if not self.can_trigger():
            return None

        try:
            if not self.condition(context):
                return None
        except Exception:
            return None

        self._last_triggered = datetime.utcnow()

        # Format title and message
        title = self.title_template.format(**context)
        message = self.message_template.format(**context)

        import uuid
        return Alert(
            alert_id=str(uuid.uuid4())[:8],
            severity=self.severity,
            title=title,
            message=message,
            source=self.name,
            metadata=context,
        )


class AlertChannel:
    """Base class for alert notification channels."""

    def send(self, alert: Alert) -> bool:
        """Send alert through the channel."""
        raise NotImplementedError


class LogAlertChannel(AlertChannel):
    """Alert channel that logs to Python logging."""

    def __init__(self, logger: Optional[logging.Logger] = None):
        self.logger = logger or logging.getLogger("feature_platform.alerts")

    def send(self, alert: Alert) -> bool:
        """Log the alert."""
        log_level = {
            AlertSeverity.INFO: logging.INFO,
            AlertSeverity.WARNING: logging.WARNING,
            AlertSeverity.ERROR: logging.ERROR,
            AlertSeverity.CRITICAL: logging.CRITICAL,
        }.get(alert.severity, logging.INFO)

        self.logger.log(
            log_level,
            f"[{alert.severity.value.upper()}] {alert.title}: {alert.message}",
        )
        return True


class WebhookAlertChannel(AlertChannel):
    """Alert channel that sends to a webhook."""

    def __init__(self, url: str, headers: Optional[Dict[str, str]] = None):
        self.url = url
        self.headers = headers or {"Content-Type": "application/json"}

    def send(self, alert: Alert) -> bool:
        """Send alert to webhook."""
        try:
            import json
            import urllib.request

            data = json.dumps(alert.to_dict()).encode("utf-8")
            request = urllib.request.Request(
                self.url,
                data=data,
                headers=self.headers,
                method="POST",
            )

            with urllib.request.urlopen(request, timeout=10) as response:
                return response.status == 200
        except Exception:
            return False


class AlertManager:
    """
    Manager for alerts.

    Handles:
    - Alert generation based on rules
    - Alert storage and retrieval
    - Alert notifications
    """

    def __init__(
        self,
        channels: Optional[List[AlertChannel]] = None,
    ):
        self.channels = channels or [LogAlertChannel()]
        self._rules: List[AlertRule] = []
        self._alerts: List[Alert] = []
        self._max_alerts = 10000

    def add_rule(self, rule: AlertRule) -> None:
        """Add an alert rule."""
        self._rules.append(rule)

    def remove_rule(self, name: str) -> bool:
        """Remove an alert rule by name."""
        for i, rule in enumerate(self._rules):
            if rule.name == name:
                del self._rules[i]
                return True
        return False

    def add_channel(self, channel: AlertChannel) -> None:
        """Add a notification channel."""
        self.channels.append(channel)

    def create_alert(
        self,
        severity: AlertSeverity,
        title: str,
        message: str,
        source: str,
        **metadata,
    ) -> Alert:
        """Create and send a new alert."""
        import uuid

        alert = Alert(
            alert_id=str(uuid.uuid4())[:8],
            severity=severity,
            title=title,
            message=message,
            source=source,
            metadata=metadata,
        )

        self._store_alert(alert)
        self._notify(alert)

        return alert

    def evaluate_rules(self, context: Dict[str, Any]) -> List[Alert]:
        """Evaluate all rules and generate alerts."""
        alerts = []

        for rule in self._rules:
            alert = rule.trigger(context)
            if alert:
                self._store_alert(alert)
                self._notify(alert)
                alerts.append(alert)

        return alerts

    def _store_alert(self, alert: Alert) -> None:
        """Store an alert."""
        self._alerts.append(alert)

        # Trim old alerts
        if len(self._alerts) > self._max_alerts:
            self._alerts = self._alerts[-self._max_alerts:]

    def _notify(self, alert: Alert) -> None:
        """Send alert to all channels."""
        for channel in self.channels:
            try:
                channel.send(alert)
            except Exception:
                pass

    def get_alerts(
        self,
        severity: Optional[AlertSeverity] = None,
        status: Optional[AlertStatus] = None,
        source: Optional[str] = None,
        limit: int = 100,
    ) -> List[Alert]:
        """Get alerts with optional filtering."""
        filtered = self._alerts

        if severity:
            filtered = [a for a in filtered if a.severity == severity]

        if status:
            filtered = [a for a in filtered if a.status == status]

        if source:
            filtered = [a for a in filtered if a.source == source]

        return filtered[-limit:]

    def get_alert(self, alert_id: str) -> Optional[Alert]:
        """Get an alert by ID."""
        for alert in self._alerts:
            if alert.alert_id == alert_id:
                return alert
        return None

    def acknowledge_alert(self, alert_id: str, user: str) -> bool:
        """Acknowledge an alert."""
        alert = self.get_alert(alert_id)
        if alert:
            alert.acknowledge(user)
            return True
        return False

    def resolve_alert(self, alert_id: str) -> bool:
        """Resolve an alert."""
        alert = self.get_alert(alert_id)
        if alert:
            alert.resolve()
            return True
        return False

    def get_active_alerts_count(self) -> int:
        """Get count of active alerts."""
        return sum(1 for a in self._alerts if a.status == AlertStatus.ACTIVE)

    def get_summary(self) -> Dict[str, Any]:
        """Get alert summary."""
        return {
            "total": len(self._alerts),
            "active": sum(1 for a in self._alerts if a.status == AlertStatus.ACTIVE),
            "acknowledged": sum(1 for a in self._alerts if a.status == AlertStatus.ACKNOWLEDGED),
            "resolved": sum(1 for a in self._alerts if a.status == AlertStatus.RESOLVED),
            "by_severity": {
                severity.value: sum(1 for a in self._alerts if a.severity == severity)
                for severity in AlertSeverity
            },
        }


# Predefined alert rules
def create_drift_alert_rule(threshold: float = 0.1) -> AlertRule:
    """Create a rule for drift detection alerts."""
    return AlertRule(
        name="drift_detection",
        condition=lambda ctx: ctx.get("drift_score", 0) > threshold,
        severity=AlertSeverity.WARNING,
        title_template="Data drift detected in {feature_view}",
        message_template="Feature {feature_name} shows drift score of {drift_score:.3f} (threshold: {threshold})",
        cooldown_minutes=60,
    )


def create_null_ratio_alert_rule(threshold: float = 0.1) -> AlertRule:
    """Create a rule for high null ratio alerts."""
    return AlertRule(
        name="high_null_ratio",
        condition=lambda ctx: ctx.get("null_ratio", 0) > threshold,
        severity=AlertSeverity.ERROR,
        title_template="High null ratio in {feature_view}",
        message_template="Feature {feature_name} has {null_ratio:.1%} null values (threshold: {threshold:.1%})",
        cooldown_minutes=30,
    )


def create_pipeline_failure_alert_rule() -> AlertRule:
    """Create a rule for pipeline failure alerts."""
    return AlertRule(
        name="pipeline_failure",
        condition=lambda ctx: ctx.get("status") == "failed",
        severity=AlertSeverity.CRITICAL,
        title_template="Pipeline {pipeline_name} failed",
        message_template="Pipeline {pipeline_name} failed at step {failed_step}: {error_message}",
        cooldown_minutes=5,
    )
